[config]
# ...


##  WAYBAR COLORS  ##
[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'


##  HYPRLAND COLORS  ##
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'


##  KITTY COLORS  ##
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/theme/kitty-colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'


##  GTK COLORS  ##
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'


##  QT COLORS  ##
[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'


##  QT COLORS METHOD-2  ##
[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'


## MIDNIGHT DISCORD  ##
[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/BetterDiscord/themes/midnight.theme.css'


##  CAVA  ##
#[templates.cava]
#input_path = '~/.config/matugen/templates/cava-colors.ini'
#output_path = '~/.config/cava/themes/your-theme'
#post_hook = "pkill -USR1 cava"


## ROFI  ##
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'


## WLOGOUT  ##
[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

## SWAYNC  ##
[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-colors.conf'
output_path = '~/.config/swaync/swaync-colors.css'
post_hook = 'swaync-client -rs'

## MICRO ##
[templates.micro]
input_path = '~/.config/matugen/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

## ZED ##
[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

## YAZI ##
[templates.yazi]
input_path = '/home/god/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

# ## PYWALFOX ##
# [templates.pywalfox]
# input_path = '/home/god/.config/matugen/templates/pywalfox-colors.json'
# output_path = '~/.cache/wal/colors.json'
# post_hook = 'pywalfox update'