# : Manager [[[

[mgr]
cwd = { fg = "#1b1c15" }

# Tab
tab_active = { fg = "#ffffff", bg = "#546524", bold = true }
tab_inactive = { fg = "#d7eb9b", bg = "#161e00" }
tab_width = 1

# Find
find_keyword = { fg = "#ba1a1a", bold = true, italic = true, underline = true }
find_position = { fg = "#ba1a1a", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6dd5c0", bg = "#6dd5c0" }
marker_cut = { fg = "#bcece2", bg = "#bcece2" }
marker_marked = { fg = "#ba1a1a", bg = "#ba1a1a" }
marker_selected = { fg = "#3a665e", bg = "#3a665e" }

# Count
count_copied = { fg = "#00201c", bg = "#bcece2" }
count_cut = { fg = "#00201c", bg = "#bcece2" }
count_selected = { fg = "#ffffff", bg = "#3a665e" }

# Border
border_symbol = " "
border_style  = { fg = "#546524" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#ffffff", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#546524", fg = "#ffffff", bold = true }
normal_alt  = { bg = "#e3e4d3", fg = "#46483c" }

# Select mode
select_main = { bg = "#5b6146", fg = "#ffffff", bold = true }
select_alt  = { bg = "#e3e4d3", fg = "#46483c" }

# Unset mode
unset_main = { bg = "#3a665e", fg = "#ffffff", bold = true }
unset_alt  = { bg = "#e3e4d3", fg = "#46483c" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#546524", bg = "#fbfaed" }
progress_error = { fg = "#ba1a1a", bg = "#fbfaed" }

# Permissions
permissions_t = { fg = "#a9af91" }
permissions_w = { fg = "#81b8ae" }
permissions_x = { fg = "#ed8080" }
permissions_r = { fg = "#45caae" }
permissions_s = { fg = "#9ec628" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#546524" }
active = { fg = "#3a665e", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#546524" }
value = { fg = "#1b1c15" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#546524", bold = true, bg = "#fbfaed" }
inactive = { fg = "#5b6146", bg = "#fbfaed" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#546524", bg = "#ffffff" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#546524" }
title = {}
hovered = { fg = "#bcece2", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#fbfaed" }
cand = { fg = "#546524" }
rest = { fg = "#ffffff" }
desc = { fg = "#1b1c15" }
separator = " ‚ñ∂ "
separator_style = { fg = "#1b1c15" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#1b1c15" }
run = { fg = "#1b1c15" }
footer = { fg = "#ffffff", bg = "#5b6146" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#3a665e" }
title_warn = { fg = "#546524" }
title_error = { fg = "#ba1a1a" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#ffdad6" },
    { name = "*", is = "exec", fg = "#410002" },

    # Fallback
    { name = "*", fg = "#1b1c15" },
    { name = "*/", fg = "#546524" },
]

# : ]]]